name: Tests being demoed

on:
  workflow_dispatch:

jobs:
  tests-being-demoed:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
      - name: Run the test being demoed
        run: mvn clean test -Dgroups=test-being-demoed
